# Generated by Django 3.2.3 on 2021-08-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gameFiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
                ('description_de', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('logo', models.CharField(blank=True, max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name_de'],
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_new', models.BooleanField(default=False)),
                ('explicit', models.BooleanField(default=False)),
                ('solution', models.CharField(max_length=80)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sound_file', models.FileField(upload_to=gameFiles.models.get_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='gameFiles.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_new', models.BooleanField(default=False)),
                ('explicit', models.BooleanField(default=False)),
                ('solution', models.CharField(max_length=80)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quiz_question', models.CharField(max_length=80)),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('option3', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='gameFiles.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_new', models.BooleanField(default=False)),
                ('explicit', models.BooleanField(default=False)),
                ('solution', models.CharField(max_length=80)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_file', models.ImageField(upload_to=gameFiles.models.get_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='gameFiles.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='game_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameFiles.gametype'),
        ),
    ]
