# Generated by Django 3.2.3 on 2021-05-14 20:13

from django.db import migrations, models
import django.db.models.deletion
import gameFiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
                ('description_de', models.TextField()),
                ('logo', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicit', models.BooleanField(default=False)),
                ('solution', models.CharField(max_length=80)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.category')),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name_de'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('categoryelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gameFiles.categoryelement')),
                ('image_file', models.ImageField(upload_to=gameFiles.models.get_upload_path)),
            ],
            bases=('gameFiles.categoryelement',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('categoryelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gameFiles.categoryelement')),
                ('quiz_question', models.CharField(max_length=80)),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('option3', models.CharField(max_length=80)),
            ],
            bases=('gameFiles.categoryelement',),
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('categoryelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gameFiles.categoryelement')),
                ('sound_file', models.FileField(upload_to=gameFiles.models.get_upload_path)),
            ],
            bases=('gameFiles.categoryelement',),
        ),
        migrations.AddField(
            model_name='categoryelement',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gameFiles.Tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='game_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameFiles.gametype'),
        ),
    ]
