# Generated by Django 3.2.3 on 2021-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('solution', 'category'), name='image_unique_solution_per_category'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('solution', 'category'), name='question_unique_solution_per_category'),
        ),
        migrations.AddConstraint(
            model_name='sound',
            constraint=models.UniqueConstraint(fields=('solution', 'category'), name='sound_unique_solution_per_category'),
        ),
    ]
