# Generated by Django 3.2.3 on 2021-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0002_auto_20210522_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
