# Generated by Django 3.2.3 on 2021-11-12 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameFiles', '0002_auto_20210812_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_new', models.BooleanField(default=False)),
                ('explicit', models.BooleanField(default=False)),
                ('solution', models.CharField(max_length=80)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hint1', models.CharField(max_length=80)),
                ('hint2', models.CharField(max_length=80)),
                ('hint3', models.CharField(max_length=80)),
                ('hint4', models.CharField(max_length=80)),
                ('hint5', models.CharField(max_length=80)),
                ('hint6', models.CharField(max_length=80)),
                ('hint7', models.CharField(max_length=80)),
                ('hint8', models.CharField(max_length=80)),
                ('hint9', models.CharField(max_length=80)),
                ('hint10', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='gameFiles.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='hints',
            constraint=models.UniqueConstraint(fields=('solution', 'category'), name='hints_unique_solution_per_category'),
        ),
    ]
