# Generated by Django 3.2.3 on 2022-01-06 20:00

import django.core.files.storage
from django.db import migrations, models
import gameFiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0003_auto_20211112_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='license',
            field=models.CharField(choices=[('CC0', 'Creative Commons Zero Public Domain'), ('CC BY', 'Creative Commons Attribution'), ('CC BY-SA', 'Creative Commons Attribution-ShareAlike')], default='CC BY', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/usb-drive', location='/Users/List/Desktop/Website_Buzzinga/buzzinga_website/media'), upload_to=gameFiles.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/usb-drive', location='/Users/List/Desktop/Website_Buzzinga/buzzinga_website/media'), upload_to=gameFiles.models.get_upload_path),
        ),
    ]
