# Generated by Django 3.2.3 on 2021-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0003_category_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryelement',
            name='private_new',
            field=models.BooleanField(default=False),
        ),
    ]
