# Generated by Django 4.2.16 on 2024-11-11 12:07

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import gameFiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gameFiles", "0004_auto_20220106_2000"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoKnowsMore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private_new",
                    models.BooleanField(default=False, verbose_name="Privat"),
                ),
                (
                    "explicit",
                    models.BooleanField(default=False, verbose_name="Explizit"),
                ),
                ("solution", models.CharField(max_length=80, verbose_name="Lösung")),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        verbose_name="Schwierigkeit",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description_de",
            field=models.TextField(verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="category",
            name="game_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.gametype",
                verbose_name="Spielart",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_de",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="private",
            field=models.BooleanField(default=False, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="gametype",
            name="name_de",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="hints",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="Schwierigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="hints",
            name="explicit",
            field=models.BooleanField(default=False, verbose_name="Explizit"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint1",
            field=models.CharField(max_length=80, verbose_name="Hinweis 1"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint10",
            field=models.CharField(max_length=80, verbose_name="Hinweis 10"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint2",
            field=models.CharField(max_length=80, verbose_name="Hinweis 2"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint3",
            field=models.CharField(max_length=80, verbose_name="Hinweis 3"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint4",
            field=models.CharField(max_length=80, verbose_name="Hinweis 4"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint5",
            field=models.CharField(max_length=80, verbose_name="Hinweis 5"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint6",
            field=models.CharField(max_length=80, verbose_name="Hinweis 6"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint7",
            field=models.CharField(max_length=80, verbose_name="Hinweis 7"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint8",
            field=models.CharField(max_length=80, verbose_name="Hinweis 8"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="hint9",
            field=models.CharField(max_length=80, verbose_name="Hinweis 9"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="private_new",
            field=models.BooleanField(default=False, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="solution",
            field=models.CharField(max_length=80, verbose_name="Lösung"),
        ),
        migrations.AlterField(
            model_name="image",
            name="author",
            field=models.CharField(max_length=50, verbose_name="Urheber"),
        ),
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="Schwierigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="explicit",
            field=models.BooleanField(default=False, verbose_name="Explizit"),
        ),
        migrations.AlterField(
            model_name="image",
            name="file_changed",
            field=models.BooleanField(default=False, verbose_name="Datei bearbeitet?"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads",
                    location="/home/S73FF3N/buzzinga-website/uploads",
                ),
                upload_to=gameFiles.models.get_upload_path,
                verbose_name="Bilddatei",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="license",
            field=models.CharField(
                choices=[
                    ("CC0", "Creative Commons Zero Public Domain"),
                    ("CC BY", "Creative Commons Attribution"),
                    ("CC BY-SA", "Creative Commons Attribution-ShareAlike"),
                ],
                max_length=100,
                verbose_name="Lizenz",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="private_new",
            field=models.BooleanField(default=False, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="image",
            name="solution",
            field=models.CharField(max_length=80, verbose_name="Lösung"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="Schwierigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="explicit",
            field=models.BooleanField(default=False, verbose_name="Explizit"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(max_length=80, verbose_name="Option 1"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(max_length=80, verbose_name="Option 2"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(max_length=80, verbose_name="Option 3"),
        ),
        migrations.AlterField(
            model_name="question",
            name="private_new",
            field=models.BooleanField(default=False, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz_question",
            field=models.CharField(max_length=150, verbose_name="Frage"),
        ),
        migrations.AlterField(
            model_name="question",
            name="solution",
            field=models.CharField(max_length=80, verbose_name="Lösung"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="difficulty",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="Schwierigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="explicit",
            field=models.BooleanField(default=False, verbose_name="Explizit"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="private_new",
            field=models.BooleanField(default=False, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="solution",
            field=models.CharField(max_length=80, verbose_name="Lösung"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="sound_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads",
                    location="/home/S73FF3N/buzzinga-website/uploads",
                ),
                upload_to=gameFiles.models.get_upload_path,
                verbose_name="Sounddatei",
            ),
        ),
        migrations.CreateModel(
            name="WhoKnowsMoreElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=80, verbose_name="Antwort")),
                ("count_id", models.IntegerField(blank=True, null=True)),
                (
                    "category_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="gameFiles.whoknowsmore",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="whoknowsmore",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gameFiles.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="whoknowsmore",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="whoknowsmore",
            name="tags",
            field=models.ManyToManyField(blank=True, to="gameFiles.tag", related_name='whoknowsmore_tags'),
        ),
        migrations.AddConstraint(
            model_name="whoknowsmore",
            constraint=models.UniqueConstraint(
                fields=("solution", "category"),
                name="whoknowsmore_unique_solution_per_category",
            ),
        ),
    ]
