# Generated by Django 4.2.16 on 2025-03-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gameFiles", "0005_whoknowsmore_alter_category_description_de_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hints",
            name="hints_unique_solution_per_category",
        ),
        migrations.RemoveConstraint(
            model_name="image",
            name="image_unique_solution_per_category",
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="question_unique_solution_per_category",
        ),
        migrations.RemoveConstraint(
            model_name="sound",
            name="sound_unique_solution_per_category",
        ),
        migrations.RemoveConstraint(
            model_name="whoknowsmore",
            name="whoknowsmore_unique_solution_per_category",
        ),
        migrations.AlterField(
            model_name="category",
            name="game_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="gameFiles.gametype",
                verbose_name="Spielart",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hints",
            unique_together={("solution", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("solution", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("solution", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="sound",
            unique_together={("solution", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="whoknowsmore",
            unique_together={("solution", "category")},
        ),
    ]
