# Generated by Django 4.2.16 on 2025-06-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gameFiles", "0006_remove_hints_hints_unique_solution_per_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizGameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("quiz_date", models.DateField()),
                ("team1_points", models.IntegerField()),
                ("team2_points", models.IntegerField()),
                ("team3_points", models.IntegerField()),
                ("team4_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameFiles.gametype",
                    ),
                ),
                (
                    "team1_users",
                    models.ManyToManyField(
                        related_name="team1_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "team2_users",
                    models.ManyToManyField(
                        related_name="team2_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "team3_users",
                    models.ManyToManyField(
                        related_name="team3_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "team4_users",
                    models.ManyToManyField(
                        related_name="team4_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hints",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="image",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="question",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="sound",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="whoknowsmore",
            name="tags",
        ),
        migrations.AlterField(
            model_name="hints",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hints",
                to="gameFiles.category",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="gameFiles.category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="gameFiles.category",
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sounds",
                to="gameFiles.category",
            ),
        ),
        migrations.AlterField(
            model_name="whoknowsmore",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whoknowsmoreelements",
                to="gameFiles.category",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
