# Generated by Django 4.2.16 on 2025-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gameFiles",
            "0007_quizgameresult_remove_hints_tags_remove_image_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    (
                        "can_change_private",
                        "Can change private status of categories and elements",
                    )
                ]
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="private",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="hints",
            name="private_new",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="image",
            name="private_new",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="question",
            name="private_new",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="private_new",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
        migrations.AlterField(
            model_name="whoknowsmore",
            name="private_new",
            field=models.BooleanField(default=True, verbose_name="Privat"),
        ),
    ]
