# Generated by Django 4.2.16 on 2025-07-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameFiles", "0008_alter_category_options_alter_category_private_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    (
                        "can_change_private",
                        "Can change private status of categories and elements",
                    ),
                    (
                        "can_view_public_elements",
                        "Can view public elements in profile table",
                    ),
                ]
            },
        ),
    ]
