# Generated by Django 4.2.16 on 2025-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameFiles", "0009_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
    ]
