# Generated by Django 5.2.4 on 2025-07-23 20:49

import django.core.files.storage
import gameFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0010_gametype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='C:\\Users\\steff\\Desktop\\buzzinga-website\\uploads'), upload_to=gameFiles.models.get_upload_path, verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='C:\\Users\\steff\\Desktop\\buzzinga-website\\uploads'), upload_to=gameFiles.models.get_upload_path, verbose_name='Sounddatei'),
        ),
    ]
