# Generated by Django 5.2.4 on 2025-07-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0011_alter_image_image_file_alter_sound_sound_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_change_private', 'Can change private status of categories and elements'), ('can_view_public_elements', 'Can view public elements in profile table'), ('can_view_noxt_menu', 'Can view the Noxt menu')]},
        ),
    ]
