# Generated by Django 5.2.4 on 2025-08-11 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gameFiles', '0012_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgameresult',
            name='quiz_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizgameresult',
            name='quizmaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizmaster_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
