# Generated by Django 5.2.4 on 2026-04-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gameFiles', '0013_quizgameresult_quiz_group_quizgameresult_quizmaster'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE gameFiles_question ADD COLUMN num_options INTEGER UNSIGNED NOT NULL DEFAULT 4;",
            reverse_sql="ALTER TABLE gameFiles_question DROP COLUMN num_options;",
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='num_options',
                    field=models.PositiveIntegerField(choices=[(2, '2'), (3, '3'), (4, '4')], default=4, verbose_name='Anzahl Optionen'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='quizgameresult',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameFiles.gametype', verbose_name='Spielart'),
        ),
        migrations.AlterField(
            model_name='quizgameresult',
            name='quiz_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='auth.group', verbose_name='Wettbewerb'),
        ),
    ]
