# Generated by Django 5.2.4 on 2026-04-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameFiles', '0014_question_num_options_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
